In [3]:
prediction_tensor = np.array([[-1,1,3],[2,3,6]])
prediction_tensor

array([[-1,  1,  3],
       [ 2,  3,  6]])

In [2]:
import numpy as np
import math

In [5]:
prediction_tensor[prediction_tensor < 0] = 0
prediction_tensor

array([[0, 1, 3],
       [2, 3, 6]])

In [10]:
epsilon = np.finfo(float).eps
print(epsilon)

2.220446049250313e-16


In [13]:
clipped_preds = np.clip(prediction_tensor, epsilon, 1. - epsilon)
clipped_preds

array([[2.22044605e-16, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [ ]:
class CrossEntropyLoss:
    def __init__(self):
        self.prediction_tensor = None
        self.label_tensor = None

    def forward(self, prediction_tensor, label_tensor):
        # Save for backward pass
        self.prediction_tensor = prediction_tensor
        self.label_tensor = label_tensor

        # Avoid log(0) by adding small epsilon
        epsilon = 1e-12
        clipped_preds = np.clip(prediction_tensor, epsilon, 1. - epsilon)

        # Compute batch cross-entropy loss
        loss = -np.sum(label_tensor * np.log(clipped_preds)) / prediction_tensor.shape[0]
        return loss

In [35]:
shifted_tensor = input_tensor - np.max(input_tensor, axis=1, keepdims=True)
shifted_tensor

array([[-4, -2,  0],
       [-4, -3,  0]])

In [50]:
input_tensor.shape[1]

3

In [47]:
input_tensor[0]

array([-1,  1,  3])

In [64]:
output_tensor = np.empty((1,2))
output_tensor   

array([[1.5e-323, 3.0e-323]])

In [68]:
input_tensor
output_tensor = np.empty((input_tensor.shape[0], input_tensor.shape[1]))

for i in range(input_tensor.shape[0]):
    summe = 0
    for k in range(input_tensor.shape[1]):
        summe += math.exp(input_tensor[i, k])
    
    for j in range(input_tensor.shape[1]):
        output_tensor[i][j] = math.exp(input_tensor[i][j]) / summe

output_tensor



array([[0.01587624, 0.11731043, 0.86681333],
       [0.01714783, 0.04661262, 0.93623955]])

In [22]:
relu_derivative

array([[False,  True,  True],
       [ True,  True,  True]])

In [23]:
input_tensor * relu_derivative

array([[0, 1, 3],
       [2, 3, 6]])

In [24]:
np.matmul(input_tensor, relu_derivative)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [16]:
input_tensor[input_tensor < 0] = 0
input_tensor

array([[0, 1, 3],
       [2, 3, 6]])

In [10]:
input_tensor.shape[0]

2

In [24]:
bias_column = np.ones((2,1))

In [25]:
np.hstack((input_tensor, bias_column))

array([[0., 1., 3., 1.],
       [2., 3., 6., 1.]])