In [2]:
import numpy as np

arr = np.random.randn(8, 5)
arr2 = np.random.randn(5, 10)
res = np.matmul(arr, arr2)
res.shape

(8, 10)

In [12]:
import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
X_max = np.max(X, axis=1, keepdims=True)  # shape: (batch_size, 1)
X_centered = X - X_max

print(X_max)
print(X_centered)

[[3]
 [6]
 [9]]
[[-2 -1  0]
 [-2 -1  0]
 [-2 -1  0]]


In [ ]:
print(np.finfo(float).eps)

AttributeError: type object 'finfo' has no attribute 'eps'